# Dockerfile para Treinamento
FROM python:3.9-slim

WORKDIR /app

# Instalar dependências de sistema (Tesseract e libs gráficas para OpenCV)
RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    libgl1-mesa-glx \
    libglib2.0-0 \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# O ponto de entrada padrão é o script de treino
CMD ["python", "src/train.py"]
